name: qr_quill
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  file_picker: ^6.0.0
  firebase_core: ^2.20.0
  firebase_storage: ^11.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_barcode_scanner: ^2.0.0
  flutter_pin_code_fields: ^2.2.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.2.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.5
  qr: ^3.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
